# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import house.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0005_auto_20160801_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.IntegerField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=250)),
                ('long_term_lease', models.BooleanField()),
                ('start_data', models.DateField()),
                ('post_data', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.user')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=house.models.upload_location)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='house.Room')),
            ],
        ),
    ]
