# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
