# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20160803_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
