# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20160806_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='post_data',
            new_name='post_date',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
