# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-06 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20160806_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='User',
        ),
    ]
