# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1000)),
                ('avatar', models.CharField(blank=True, max_length=1000)),
                ('cellNumber', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
