# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import user_info.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='../media/None/icon-user-default.png', upload_to=user_info.models.upload_location),
        ),
    ]
