# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20160801_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellNumber',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
